baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "paper"

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"

disqusShortname = 'tech-hub-5'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'emberauclair'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Amber Padgett'
  bio = 'Amber is a NYC-based coder with a flair for creating elegant solutions in Python and Java. When not immersed in the digital realm, she explores the artistry of stippling and the nuances of color science'

  # misc
  math = true                               # enable KaTeX math typesetting globally